### ISSUE TITLE
Topo call get_rank_idx_by_group_host_idx is only correct on host 0

### ISSUE THREAD

**Issue by bws** [gvallee/dpu_offload_service#290]
Configured with 2 nodes and 32 ppn this topo call returns the correct local_rank_idx only on the first host. This is a more serious issue as this call is required to build any sort of Topo ring. Confirmed to be an issue on git hash: d8e1caaaf707476a91589aadf14c41be9151f6bf (Nov 3, 2023)

For example:

My rank is: 28 local_idx: 28
My rank is: 30 local_idx: 30
My rank is: 1 local_idx: 1 o
My rank is: 20 local_idx: 20
My rank is: 14 local_idx: 14
My rank is: 21 local_idx: 21
My rank is: 11 local_idx: 11
My rank is: 8 local_idx: 8 o
My rank is: 18 local_idx: 18
My rank is: 25 local_idx: 25
My rank is: 26 local_idx: 26
My rank is: 5 local_idx: 5 o
My rank is: 6 local_idx: 6 o
My rank is: 9 local_idx: 9 o
My rank is: 19 local_idx: 19
My rank is: 15 local_idx: 15
My rank is: 24 local_idx: 24
My rank is: 10 local_idx: 10
My rank is: 27 local_idx: 27
My rank is: 29 local_idx: 29
My rank is: 4 local_idx: 4 o
My rank is: 22 local_idx: 22
My rank is: 17 local_idx: 17
My rank is: 7 local_idx: 7 
My rank is: 23 local_idx: 23
My rank is: 3 local_idx: 3 
My rank is: 13 local_idx: 13
My rank is: 31 local_idx: 31
My rank is: 12 local_idx: 12
My rank is: 2 local_idx: 2 
My rank is: 58 local_idx: 0
My rank is: 33 local_idx: 0
My rank is: 37 local_idx: 0
My rank is: 59 local_idx: 0
My rank is: 41 local_idx: 0
My rank is: 60 local_idx: 0
My rank is: 55 local_idx: 0
My rank is: 43 local_idx: 0
My rank is: 44 local_idx: 0
My rank is: 38 local_idx: 0
My rank is: 63 local_idx: 0
My rank is: 54 local_idx: 0
My rank is: 57 local_idx: 0
My rank is: 56 local_idx: 0
My rank is: 36 local_idx: 0
My rank is: 45 local_idx: 0
My rank is: 61 local_idx: 0
My rank is: 52 local_idx: 0
My rank is: 39 local_idx: 0
My rank is: 51 local_idx: 0
My rank is: 34 local_idx: 0
My rank is: 35 local_idx: 0
My rank is: 49 local_idx: 0
My rank is: 46 local_idx: 0
My rank is: 42 local_idx: 0
My rank is: 50 local_idx: 0
My rank is: 40 local_idx: 0
My rank is: 53 local_idx: 0
My rank is: 62 local_idx: 0
My rank is: 47 local_idx: 0
My rank is: 0 local_idx: 0 
My rank is: 16 local_idx: 16
My rank is: 48 local_idx: 0
My rank is: 32 local_idx: 0

**Comment by bws** [comment]
Adding important context on this. The local_idx comes from this code block:

        /* Get which local rank this is */
        ucc_rank_t my_rank = UCC_TL_TEAM_RANK(team);
        size_t my_local_rank_idx = -1;
        dstatus = get_rank_idx_by_group_host_idx(econtext->engine, team->offloading_uid, team_data->host_segments.host_idx, 
                                                 my_rank, &my_local_rank_idx);
        if (dstatus) {
            ucs_error("ERROR: get_rank_idx_by_group_host_idx failed\n");
            return UCC_ERR_NO_RESOURCE;
        }

**Comment by gvallee** [comment]
Question: what is in `team_data->host_segments.host_idx`? Can you confirm it has the appropriate host index?

**Comment by bws** [comment]
Yes, it confirms as correct. Here is the printf:

        fprintf(stderr, "My rank is: %d local_idx: %ld host_idx: %ld\n", 
                my_rank, my_local_rank_idx, team_data->host_segments.host_idx);

Sample output:

My rank is: 13 local_idx: 13 host_idx: 0
My rank is: 7 local_idx: 7 host_idx: 0
My rank is: 1 local_idx: 1 host_idx: 0
My rank is: 9 local_idx: 9 host_idx: 0
My rank is: 30 local_idx: 30 host_idx: 0
My rank is: 2 local_idx: 2 host_idx: 0
My rank is: 20 local_idx: 20 host_idx: 0
My rank is: 21 local_idx: 21 host_idx: 0
My rank is: 16 local_idx: 16 host_idx: 0
My rank is: 23 local_idx: 23 host_idx: 0
My rank is: 5 local_idx: 5 host_idx: 0
My rank is: 25 local_idx: 25 host_idx: 0
My rank is: 3 local_idx: 3 host_idx: 0
My rank is: 6 local_idx: 6 host_idx: 0
My rank is: 26 local_idx: 26 host_idx: 0
My rank is: 31 local_idx: 31 host_idx: 0
My rank is: 24 local_idx: 24 host_idx: 0
My rank is: 12 local_idx: 12 host_idx: 0
My rank is: 17 local_idx: 17 host_idx: 0
My rank is: 28 local_idx: 28 host_idx: 0
My rank is: 15 local_idx: 15 host_idx: 0
My rank is: 8 local_idx: 8 host_idx: 0
My rank is: 4 local_idx: 4 host_idx: 0
My rank is: 14 local_idx: 14 host_idx: 0
My rank is: 18 local_idx: 18 host_idx: 0
My rank is: 29 local_idx: 29 host_idx: 0
My rank is: 19 local_idx: 19 host_idx: 0
My rank is: 0 local_idx: 0 host_idx: 0
My rank is: 10 local_idx: 10 host_idx: 0
My rank is: 11 local_idx: 11 host_idx: 0
My rank is: 27 local_idx: 27 host_idx: 0
My rank is: 22 local_idx: 22 host_idx: 0
My rank is: 51 local_idx: 0 host_idx: 1
My rank is: 60 local_idx: 0 host_idx: 1
My rank is: 40 local_idx: 0 host_idx: 1
My rank is: 36 local_idx: 0 host_idx: 1
My rank is: 44 local_idx: 0 host_idx: 1
My rank is: 58 local_idx: 0 host_idx: 1
My rank is: 59 local_idx: 0 host_idx: 1
My rank is: 35 local_idx: 0 host_idx: 1
My rank is: 63 local_idx: 0 host_idx: 1
My rank is: 39 local_idx: 0 host_idx: 1
My rank is: 41 local_idx: 0 host_idx: 1
My rank is: 62 local_idx: 0 host_idx: 1
My rank is: 47 local_idx: 0 host_idx: 1
My rank is: 49 local_idx: 0 host_idx: 1
My rank is: 46 local_idx: 0 host_idx: 1
My rank is: 52 local_idx: 0 host_idx: 1
My rank is: 57 local_idx: 0 host_idx: 1
My rank is: 55 local_idx: 0 host_idx: 1
My rank is: 50 local_idx: 0 host_idx: 1
My rank is: 61 local_idx: 0 host_idx: 1
My rank is: 53 local_idx: 0 host_idx: 1
My rank is: 37 local_idx: 0 host_idx: 1
My rank is: 43 local_idx: 0 host_idx: 1
My rank is: 32 local_idx: 0 host_idx: 1
My rank is: 56 local_idx: 0 host_idx: 1
My rank is: 33 local_idx: 0 host_idx: 1
My rank is: 48 local_idx: 0 host_idx: 1
My rank is: 38 local_idx: 0 host_idx: 1
My rank is: 45 local_idx: 0 host_idx: 1
My rank is: 34 local_idx: 0 host_idx: 1
My rank is: 42 local_idx: 0 host_idx: 1
My rank is: 54 local_idx: 0 host_idx: 1

**Comment by gvallee** [comment]
#291 fixes it
